# https://docs.readthedocs.io/en/latest/yaml-config.html
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.8"

formats:
  - htmlzip
  - epub

python:
  install:
    - requirements: ci/rtd-requirements.txt
